//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int Id { get; set; }
        public string AWS_Asset { get; set; }
        public string AWS_bucket { get; set; }
        public string Azure_Asset { get; set; }
        public string DestContainer { get; set; }
        public string Filename { get; set; }
        public string blobstorageURI { get; set; }
        public string AssetId { get; set; }
        public Nullable<bool> CopyStatus { get; set; }
        public Nullable<bool> MediaUpdateStatus { get; set; }
        public Nullable<bool> Encoded_ { get; set; }
        public Nullable<bool> Encrypted { get; set; }
        public Nullable<System.DateTime> CopyStartdate { get; set; }
        public Nullable<System.DateTime> MediaUpdatedate { get; set; }
    }
}
